frontend/controllers/CabinetController.php
<?php

namespace frontend\controllers;
use frontend\models\BankCard;
use frontend\models\Policy;
use frontend\models\User;
use Yii;
use yii\base\DynamicModel;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\HttpException;

class CabinetController extends Controller
{
    public $layout = 'main';
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'profile', 'change-password', 'buy', 'test'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $user = Yii::$app->user->id;
        $policies = Policy::find()->where('user_id = :user', [':user' => $user])->orderBy('date_at DESC')->all();
        return $this->render('index', [
            'policies' => $policies
        ]);
    }

    public function actionProfile()
    {
        $user = User::findOne(Yii::$app->user->id);

        if($user->load(Yii::$app->request->post()) && $user->validate()){
            $user->save(false);
            Yii::$app->session->setFlash('success', 'Данные успешно обновлены');
        }

        return $this->render('profile', ['user' => $user]);
    }

    public function actionChangePassword()
    {
        $user = User::findOne(Yii::$app->user->id);

        $password = '';
        $password_repeat = '';

        $model = new DynamicModel(compact('password', 'password_repeat'));
        $model->addRule(['password', 'password_repeat'], 'required', ['message' => 'Поле не заполнено'])
            ->addRule('password', 'compare', ['message' => 'Пароли не совпадают'])
            ->addRule(['password', 'password_repeat'], 'string', ['min' => 6, 'message' => 'Пароль должен содержать не менее 6 символов', 'tooShort' => 'Пароль должен содержать не менее 6 символов']);

        if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post()) && $model->validate()){
           $user->setPassword($model->password);
            if($user->save(false)){
                Yii::$app->session->setFlash('success', 'Пароль успешно изменен');
            }else{
                Yii::$app->session->setFlash('alert', VarDumper::dumpAsString($user->errors));
            }
        }
        return $this->render('password', ['model' => $model]);
    }

    public function actionBuy($policyNumber = null, $orderId = null)
    {
        if(is_null($policyNumber)){
            throw new HttpException('Policy not chosen.');
        }

        $policy = Policy::findByNumber($policyNumber);

        if($policy->user_id !== Yii::$app->user->id){
            throw new HttpException('User is not owner of this policy');
        }

        $class = $policy->class;
        $model = new $class;

        if(!is_null($orderId)){
            return $this->render('//_payment/vazhno_result',[
                'model'     => $model,
                'policy'    => $policy,
                'orderId'   => $orderId
            ]);

        }else{

            return $this->render('//_payment/'.$model->code, [
                'policy'    => $policy,
                'card'      => new BankCard()
            ]);
        }
    }
}

frontend/views/cabinet/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
?>
<h1>Мои полиса</h1>
<?php if(count($policies) > 0):?>
    <table class="table">
        <tr>
            <th>Дата оформления</th>
            <th>Тип</th>
            <th>Номер полиса</th>
            <th>Название страховой</th>
            <th>Статус</th>
            <th>Стоимость</th>
            <th>Дата окончания полиса</th>
            <th>Ссылка на скачивание pdf</th>
        </tr>

    <?php foreach($policies as $i => $policy):?>
        <tr>
            <td><?=$policy->date_at;?></td>
            <td><?=$policy->insurance_type;?></td>
            <td><?=$policy->number;?></td>
            <td><?=$policy->insurance_company;?></td>
            <td>
                <?=$policy->status;?>
                <?php if($policy->status === \frontend\models\Policy::STATUS_WAIT):?>
                    <br>
                    <?= Html::a('Оплатить', ['/cabinet/buy', 'policyNumber' => $policy->number]);?>
                <?php endif;?>
            </td>
            <td><?=($policy->calculation_cost) ? $policy->calculation_cost : '-';?></td>
            <td><?=($policy->date_end) ? $policy->date_end: '-';?></td>
            <td><?= ($policy->url_pdf) ? Html::a('Скачать', '/files/'.$policy->url_pdf, ['target' => '_blank']) : ' - ';?></td>
        </tr>
    <?php endforeach;?>
    </table>
<?php else:?>
    <p><code>Оформленных полисов нет</code></p>
<?php endif;?>

frontend/views/cabinet/password.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<div class="row">
    <div class="col-md-12">
        <?= (Yii::$app->session->getFlash('success')) ? '<div class="alert alert-success" role="alert"><b>'.Yii::$app->session->getFlash('success').'</b></div>' : '';?>
        <?= (Yii::$app->session->getFlash('alert')) ? '<div class="alert alert-danger" role="alert"><b>'.Yii::$app->session->getFlash('alert').'</b></div>' : '';?>
    </div>
</div>
<h5 class="page-header"><b>Изменение пароля:</b></h5>
<div class="row">
    <div class="col-md-6">
        <?php $form = ActiveForm::begin([
            'id'    => 'change-password'
        ]);?>
        <?= $form->field($model, 'password')->passwordInput()->label('Новый пароль');?>
        <?= $form->field($model, 'password_repeat')->passwordInput()->label('Повторный пароль');?>
        <div class="pull-right">
            <?= Html::submitButton('Изменить', ['class' => 'btn btn-success']);?>
        </div>
        <?php ActiveForm::end();?>
    </div>
</div>

frontend/views/cabinet/profile.php
<?php
use yii\widgets\ActiveForm;
use frontend\models\User;
use yii\helpers\Html;
use yii\jui\DatePicker;
use frontend\models\Document;
use frontend\models\Country;
?>
<div>
    <?php $form = ActiveForm::begin([]);?>
        <div class="row">
            <div class="col-md-12">
                <?= (Yii::$app->session->getFlash('success')) ? '<div class="alert alert-success" role="alert"><b>'.Yii::$app->session->getFlash('success').'</b></div>' : '';?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5 class="page-header"><b>Учетные данные:</b></h5>
                <?= $form->field($user, 'surname')->textInput();?>
                <?= $form->field($user, 'name')->textInput();?>
                <?= $form->field($user, 'middle_name')->textInput();?>
                <?= $form->field($user, 'sex')->dropDownList(User::$SEX);?>
                <?= $form->field($user, 'nationality')->dropDownList(Country::getCountries());?>
                <?= $form->field($user, 'date_born')->widget(DatePicker::className(),[
                    'dateFormat'=> 'dd.MM.yyyy',
                    'language'  => 'ru',
                    'clientOptions'   => [
                        'changeMonth'   => true,
                        'changeYear'    => true,
                        'yearRange'     => '-110:+0',
                        'defaultDate'   => '-25y',
                        'maxDate'       => '0'
                    ]
                ]);?>
                <?= $form->field($user, 'place_born')->textInput();?>
                <?= $form->field($user, 'phone')->textInput();?>
                <?= $form->field($user, 'email')->textInput();?>
            </div>
            <div class="col-md-6">
                <h5 class="page-header"><b>Удостоверяющие документы:</b></h5>
                <?= $form->field($user, 'document_type')->dropDownList(Document::getTypes());?>
                <?= $form->field($user, 'document_serie')->textInput();?>
                <?= $form->field($user, 'document_date')->widget(DatePicker::className(),[
                    'dateFormat'=> 'dd.MM.yyyy',
                    'clientOptions'   => [
                        'changeMonth'   => true,
                        'changeYear'    => true,
                        'yearRange'     => '-90:+0',
                        'maxDate'       => '0'
                    ]
                ]);?>
                <?= $form->field($user, 'inn')->textInput();?>
                <?= $form->field($user, 'document_number')->textInput();?>
                <?= $form->field($user, 'document_by')->textInput();?>
                <h5 class="page-header"><b>Адрес места жительства или регистрации:</b></h5>
                <?= $form->field($user, 'city')->textInput();?>
                <?= $form->field($user, 'house')->textInput();?>
                <?= $form->field($user, 'apartment')->textInput();?>
                <?= $form->field($user, 'street')->textInput();?>
                <?= $form->field($user, 'housing')->textInput();?>

            </div>
            <div class="pull-right">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']);?>
            </div>
        </div>
    <?php ActiveForm::end();?>
</div>