backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use backend\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\models\PasswordResetRequestForm;
use frontend\models\Policy;
use frontend\models\ResetPasswordForm;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use frontend\models\LoginForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            /*'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],*/
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
		$this->layout = 'main-index';
        return $this->render('index');
    }

	/*
	 * Выводит статические страницы сайта
	 * about|quotes|personal-insurance|corporate-insurance|losses|useful|news
	 */
    public function actionPage($page)
    {
        return $this->render($page);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionForgetPassword()
    {
        $model = new PasswordResetRequestForm();

        if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post()) && $model->validate()){
            $model->sendEmail();
            return $this->render('requestPasswordResetTokenSent');

        }else{
            return $this->render('requestPasswordResetToken', ['model' => $model]);
        }
    }

    public function actionResetPassword($token)
    {
        try{
            $model = new ResetPasswordForm($token);

            if(Yii::$app->request->isPost && $model->load(Yii::$app->request->post()) && $model->validate()){
                if($model->resetPassword()){
                    return $this->render('resetPasswordSuccess');
                }
            }

            return $this->render('resetPassword', ['model' => $model]);
        }catch (\Exception $e){
            return $this->render('error', [
                'name'      => 'Ошибка доступа',
                'message'   => $e->getMessage()
            ]);
        }
    }
}

frontend/views/site/about.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'О компании';

?>

<h1><?= Html::encode($this->title) ?></h1>

<p><b>Lookins — online-сервис страховых услуг.</b></p>
<p>Вам больше не нужно тратить время на поездки в офисы страховых компаний или переплачивать посредникам. Более того, Вам больше не нужно ничего искать на сайтах страховых компаний и сравнивать
	условия, выбирая лучшие. Мы это сделали за вас. Просто введите нужные вам параметры страховки, распечатайте полис и пользуйтесь страховой защитой от ведущих страховых компаний России.</p>

<p><b>Мы беспристрастны</b></p>
<p>Lookins предлагает услуги различных страховых компаний, и для нас не имеет значения полис какой из них Вы выберете. Главное, чтобы приобретя полис,
	Вы могли быть уверены в надежности своей защиты! Мы работаем только с крупнейшими, зарекомендовавшими себя на рынке страховыми компаниями.</p>

<p><b>Почему Lookins?</b></p>
<p>Это образ, который совмещает в себе жизнелюбие, надёжность и уверенную защиту.</p>
<p>Просто «лукните» страховку на <a href="<?=Url::toRoute(['/site/index'])?>">www.lookins.ru</a></p>

<p><b>Наша главная цель</b></p>
<p>Предоставить Вам полис максимально быстро, чтобы вы не отвлекались от жизни, выбирая и сравнивая страховки, а могли получить все и сразу максимально просто: увидел, выбрал, распечатал полис,
	и Ваши риски теперь под надежной защитой одной из ведущих страховых компаний России.</p>

frontend/views/site/contacts.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'Контакты';

?>

<h1><?= Html::encode($this->title) ?></h1>

<p><b>ООО "Капасити"</b></p>
<p>E-mail: <a href="mailto:info@lookins.ru">info@lookins.ru</a></p>
<p>Телефон: +7 (495) 410-10-93</p>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="main">
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

</div>
</div>

frontend/views/site/how-this-work.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'Как это работает';

?>

<h1><?= Html::encode($this->title) ?></h1>

<p>Вы выбираете необходимый Вам вид страхования, например, хотите застраховать имущество.</p>
<p>Вводите в специальную форму необходимую для расчёта стоимости страхования параметры и мы предложим Вам варианты в разных компаниях.</p>
<p>Вы выбираете страховую компанию и оплачиваете полис удобным для Вас способом.</p>
<p>После оплаты Вы получаете страховой полис по электронной почте. Мы также отправляем Вам sms-сообщение с номер полиса и телефонами сервисной службы страховой компании,
	чтобы они были у Вас всегда под рукой.</p>
<p>Полис также будет храниться в Вашем личном кабинете на нашем сайте. Просто распечатайте полис и теперь Ваши риски под надежной защитой!</p>

frontend/views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Страховой онлайн супермаркет';
$this->registerMetaTag([
	'description' => 'Покупка страхового полиса онлайн. После оформления страховки и онлайн оплаты, Ваш страховой полис придёт к Вам на электронную почту. Возможность приобрести медицинсткую
	туристическую страховку для выезжающих за рубеж, страхование недвижимости, здоровья, от несчастных случаев, транспорта.',

	//'Оформление страховки онлайн выезжающих за рубеж, страхование нежвижимости и от несчастных случаев. После  Онлайн оформление страхового полиса выезжающих за границу. Оформление
	//страховки на недвижимое имущество и онлайн страхование от несчастных случаев.',
	//Группа «АльфаСтрахование» предлагает купить медицинскую туристическую страховку для выезжающих за рубеж онлайн. Мы также осуществляем ВЗР страхование путешественников для Шенгенской визы в Москве и Санкт-Петербурге
	//Предложения для путешественников: страхование туристов от невыезда, страхование багажа, медицинское и имущественное, от несчастных случаев - купить онлайн
	//Покупайте страховой полис как вам удобно: по телефону, на сайте или с помощью онлайн консультанта. Страхование путешественников, недвижимости, здоровья, транспорта.
]);
?>
        <div class="look">
            <ul>
                <li>
                    <img src="img/l1.png" class="look_image" />
                    <div class="text_look text1">
                        <p>Страхование недвижимости</p>
                        <a href="#" class="a_buy">Купить</a>
                    </div>
                </li>
                <li>
                    <img src="img/l2.png" class="look_image" />
                    <div class="text_look">
                        <p>Страхование выезжающих за рубеж</p>
                        <a href="<?=Url::toRoute(['/travel-insurance.html'])?>" class="a_buy">Купить</a>
                    </div>
                </li>
                <li>
                    <img src="img/l3.png" class="look_image" />
                    <div class="text_look">
                        <p>Страхование от несчастных случаев</p>
                        <a href="<?= Url::to(['/live-insurance.html']);?>" class="a_buy">Купить</a>

                    </div>
                </li>
            </ul>
        </div>

<!--    	<div class="type">
        	<ul>
            	<li>
                	<div class="type_block">
                    	<p>ОСАГО</p>
                        <a href="<?=Url::toRoute(['/site/page', 'page'=>'osago'])?>" class="a_buy">Купить</a>
                    </div>
                </li>
                <li>
                	<div class="type_block">
                    	<p>КАСКО</p>
                        <a href="<?=Url::toRoute(['/site/page', 'page'=>'kasko'])?>" class="a_buy">Купить</a>
                    </div>
                </li>
            </ul>
        </div>
-->
        <div class="step">
            <h2>3 шага оформления страховки:</h2>
            <ul>
                <li>
                    <p><em>1</em> Выберите вид страхования</p>
                    <img src="img/step1.png" />
                    <img src="img/line1.png" class="line1" />
                </li>
                <li>
                    <p><em>2</em> Оплатите онлайн</p>
                    <img src="img/step2.png" />
                    <img src="img/line2.png" class="line2" />
                </li>
                <li>
                    <p><em>3</em> Получите Ваш полис на Email</p>
                    <img src="img/step3.png" />
                </li>
            </ul>
        </div>

		<div class="logotip">
            <h2>Наши партнеры</h2>
            <ul>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log7.png" /></a></li>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log8.png" /></a></li>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log1.png" /></a></li>
            </ul>
            <ul>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log6.png" /></a></li>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log9.png" /></a></li>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log10.png" /></a></li>
            </ul>
            <ul>
                <li><a href="<?=Url::toRoute(['/site/page', 'page'=>'partners'])?>"><img src="img/log11.png" /></a></li>
                <li></li>
                <li></li>
            </ul>

        </div>

frontend/views/site/kasko.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'Онлайн оформление каско';

?>
	<iframe src="http://www.sravnikupi.ru/products/casco/?pid=320_366_338_476" width="1000" height="1275" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
			hspace="0" vspace="0">Ваш браузер не поддерживает плавающие фреймы!</iframe>

frontend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model frontend\models\LoginForm */

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Для входа в систему заполните поля:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?><?= Html::a('Забыли пароль?', ['/forget-password.html']);?>
    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
</div>

frontend/views/site/osago.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'Оформление онлайн осаго';

?>
	<iframe src="http://www.sravnikupi.ru/products/osago/?pid=320_366_339_4605" width="1000" height="1000" marginwidth="0" marginheight="0" scrolling="no" frameborder="0"
			hspace="0" vspace="0" allowTransparency>Ваш браузер не поддерживает плавающие фреймы!</iframe>

frontend/views/site/partners.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'Партнёры';

?>

<h1><?= Html::encode($this->title) ?></h1>

<p><b>ЗАО «Страховая группа «УралСиб»</b> - АГ2015-67 от 01.02.2015 г.</p>

<p><b>ОСАО «Ресо-гарантия»</b> - РГ-Б-18582869 от 06.02.2015 г.</p>

<p><b>ОСАО «ИНГОССТРАХ»</b> - 4340925-8/15 от 11.06.2015 г.</p>

<p><b>ООО "СК "Независимость"</b> - НП-002-06/2015-000039 от 03.06.2015</p>

<p><b>ООО «ВТБ Страхование»</b> - АД-001/2015 от 10.06.2015</p>

<p><b>АО «СОГАЗ»</b> - 18-83-14-15 от 26.06.2015</p>

<p><b>ООО «Страховая Компания «Согласие»</b> - 0009170-05153/15А от 10.08.2015</p>

frontend/views/site/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = 'Восстановление пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните поле email. Ссылка на сброс пароля будет направлена на указанную почту.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group pull-right">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetTokenSent.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

?>
<div class="site-reset-password-sent">
    <h3><b>Инструкции по сбросу пароля отправлены Вам на почту.</b></h3>
</div>

frontend/views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = 'Установка нового пароля на сайте Lookins.ru';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, установите новый пароль:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group pull-right">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPasswordSuccess.php
<?php
use yii\helpers\Html;
$this->title = 'Новый пароль успешно сохранен';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>
    <p><?= Html::a('Перейти на главну страницу', ['/']);?></p>
    <p><?= Html::a('Перейти на форму авторизации', ['/site/login']);?></p>
</div>

frontend/views/site/signup.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                <?= $form->field($model, 'username') ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>